name: Bug Report
description: Report a problem with Trimly
title: "[Bug]: "
labels: ["bug"]
assignees:
  - usamaraajput

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Trimly! Please complete the following so we can reproduce and fix the bug.

  - type: input
    id: bug_summary
    attributes:
      label: Bug Summary
      description: Briefly describe the issue
      placeholder: e.g. "Crash when processing input text"
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: What are the exact steps to trigger this bug?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g. "The output audio should have included chunk 3"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: e.g. "It skipped chunk 3 entirely"
    validations:
      required: true

  - type: input
    id: system_info
    attributes:
      label: System Info
      description: OS, Python/Go version, FFmpeg version, etc.
      placeholder: e.g. "Windows 11, Python 3.11.4, FFmpeg 6.1"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Logs, screenshots, or anything else useful
      placeholder: Paste logs or explain further if needed
    validations:
      required: false
